// <auto-generated />
namespace Models.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class InitalDBCreation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitalDBCreation));
        
        string IMigrationMetadata.Id
        {
            get { return "201308111603396_InitalDBCreation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
