// <auto-generated />
namespace Models.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddClusters : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddClusters));
        
        string IMigrationMetadata.Id
        {
            get { return "201308111819397_AddClusters"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
