// <auto-generated />
namespace Models.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ClusterCoordinator : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClusterCoordinator));
        
        string IMigrationMetadata.Id
        {
            get { return "201401260810326_ClusterCoordinator"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
