// <auto-generated />
namespace Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ODFThatConf1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ODFThatConf1));
        
        string IMigrationMetadata.Id
        {
            get { return "201508081632194_ODFThatConf1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
