// <auto-generated />
namespace Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddCommitmentLocation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCommitmentLocation));
        
        string IMigrationMetadata.Id
        {
            get { return "201603220312337_AddCommitmentLocation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
